# Generated by Django 6.0.1 on 2026-02-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='original_url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_key',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
