# Generated by Django 6.0.1 on 2026-02-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slinks', '0002_alter_shortlink_original_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_key',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
