# Generated by Django 6.0.1 on 2026-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slinks', '0003_alter_shortlink_short_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
